version: '3'

tasks:
  silent: true
  init:
    silient: true
    desc: "Set up the OpenTofu Project"
    # take inputs for name, description and tier
    inputs:
      - name: name
        desc: "Name of the environment"
      - name: description
        desc: "Description of the environment"
      - name: tier
        desc: "Tier of the environment"
    cmds:
      - echo "Setting up OpenTF..."
      - |
        name={{.name}}
        description="{{.description}}"
        tier={{.tier}}
        
        # if name is not provided, throw error and exit
        if [ -z "$name" ]; then
          echo "Name is required"
          exit 1
        fi

        # if description is not provided, set it to "No description"
        if [ -z "$description" ]; then
          description="No description"
        fi

        # if tier is not provided, set it to 1
        if [ -z "$tier" ]; then
          tier=1
        fi

        echo "Name: $name"
        echo "Description: $description"
        echo "Tier: $tier"
        echo "CWD: {{.CURRENT_DIR}}"

        # Create `name` folder as a new project
        # Throw error if folder already exists
        if [ -d "$name" ]; then
          echo "Project already exists"
          exit 1
        else
          mkdir {{.CURRENT_DIR}}/$name
        fi
        
        # Copy Base folder relative this Taskfile to `name` folder
        cp -r {{.CURRENT_DIR}}/modules/otf/boiler/* {{.CURRENT_DIR}}/$name/
        echo "# ${name}" > {{.CURRENT_DIR}}/$name/README.md
        echo "${description}" >> {{.CURRENT_DIR}}/$name/README.md
        echo "TIER=${tier}" > {{.CURRENT_DIR}}/$name/setup.config
        echo "TF_VERSION=1.8" >> {{.CURRENT_DIR}}/$name/setup.config
        echo "Project created successfully"

